gh #233 dsAudio Enhance python tests
rdkcentral/rdk-halif-test-device_settings pull request #234
Opened 2024-10-18 14:35 UTC by bhanucbp

- Updated the L3 tests to avoid the repeated code
- Added ds helper class
- Updated dsAudio class to deploy the binaries which are listed in configuration file to target

2024-10-18 16:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdk-halif-test-device_settings?pullRequest=234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdk-halif-test-device_settings?pullRequest=234) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: bhanucbp<br/>:x: Bhanu Prakash<br/><hr/>**Bhanu Prakash** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdk-halif-test-device_settings?pullRequest=234) it.</sub>

2024-10-25 15:23 UTC, Ulrond requested changes
nearly

2024-10-25 15:23 UTC, Ulrond commented on host/tests/dsClasses/dsAudio_test_suite.yml
> +          arguments: ""
`arguments` should be removed.

2024-10-25 15:23 UTC, Ulrond commented on host/tests/dsClasses/dsAudio_test_suite.yml
> +          - "../../../bin/hal_test"
`should be a list of directories to copy`

2024-10-26 20:15 UTC, bhanucbp commented on host/tests/dsClasses/dsAudio.py
> +    def __init__(self, deviceProfilePath:str, session=None, devicePath="/tmp"):
done

2024-10-26 20:17 UTC, bhanucbp commented on host/tests/dsClasses/dsAudio.py
> +        self.menuConfig = os.path.join(dir_path, "dsAudio_test_suite.yml")
done

2024-10-29 09:58 UTC, Ulrond submitted a review, later dismissed
only conversations to resolve

2024-10-29 09:58 UTC, Ulrond commented on host/tests/dsClasses/dsAudio.py
> +        self.utMenu        = UTSuiteNavigatorClass(self.menuConfig, self.moduleName, session, devicePath)
have updated this

2024-11-12 14:26 UTC, bhanucbp commented on host/tests/L3_TestCases/dsAudio/dsAudioHelperClass.py
> +            for s in streamPaths:
changed the variable name

2024-11-12 17:57 UTC, hari22yuva approved these changes
looks ok

2024-11-12 18:17 UTC, srinivasgtl approved these changes
ship it.

2024-11-12 18:18 UTC, merged